spring:
  application:
    name: backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/nanny_hub_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


server:
  port: ${PORT:8080}
#  servlet:
#    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs